[general]
import = [
    "/local/home/toromano/.config/alacritty/alacritty-theme/themes/solarized_dark.toml",
    "/local/home/toromano/.config/alacritty/common.toml"
]

[terminal.shell]
    program = "/local/home/toromano/.cargo/bin/nu"
    args = ["-l"]
