[general]
import = [
    "/local/home/toromano/.config/alacritty/alacritty-theme/themes/solarized_dark.toml",
    "/local/home/toromano/.config/alacritty/test.toml"
]

[font.normal]
family = "Iosevka"
style = "Medium"
